# Generated by Django 3.1.7 on 2021-04-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_notes_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='download',
            field=models.FileField(default='', upload_to='notess'),
        ),
    ]
