# Generated by Django 3.1.7 on 2021-04-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210407_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='download',
            field=models.FileField(default='', upload_to='documents'),
        ),
    ]
