# Generated by Django 3.1.7 on 2021-04-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210407_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='download',
            new_name='pdf_file',
        ),
    ]
