# Generated by Django 3.1.7 on 2021-03-04 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contact_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
