# Generated by Django 3.1.7 on 2021-04-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210407_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='pdf_file',
            field=models.FileField(default='', upload_to='documents'),
        ),
    ]
