# Generated by Django 3.1.7 on 2021-04-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210409_0908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
    ]
