# Generated by Django 3.1.7 on 2021-03-08 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_course_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='questions',
            new_name='question',
        ),
    ]
