# Generated by Django 3.1.7 on 2021-03-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_subject_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
