# Generated by Django 3.1.7 on 2021-03-10 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_subject_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sub',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.syllabus'),
        ),
    ]
