# Generated by Django 3.1.7 on 2021-03-10 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210310_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date_time',
            new_name='pub_date',
        ),
    ]
