# Generated by Django 3.1.7 on 2021-03-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_blog_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='marks',
            field=models.IntegerField(default=5),
        ),
    ]
