# Generated by Django 3.1.7 on 2021-03-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_questions_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='course',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='sub',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='subject',
        ),
        migrations.DeleteModel(
            name='syllabus',
        ),
    ]
