# Generated by Django 3.1.7 on 2021-03-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='snippet',
            field=models.CharField(default='click to read more', max_length=255),
        ),
    ]
