# Generated by Django 3.1.7 on 2021-03-13 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_comment1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment1',
            new_name='commentblog',
        ),
    ]
