# Generated by Django 3.1.7 on 2021-03-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='branch',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='filetype',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='notesfile',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='forum',
            name='subject',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='uploadingdate',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
