# Generated by Django 3.1.7 on 2021-03-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20210314_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='branch',
        ),
    ]
