# Generated by Django 3.1.7 on 2021-03-14 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_remove_forum_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='filetype',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='notesfile',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='uploadingdate',
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('body', models.TextField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.forum')),
            ],
        ),
    ]
