# Generated by Django 3.1.7 on 2021-03-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20210314_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='snippet',
            field=models.CharField(default='read more', max_length=500),
        ),
    ]
