# Generated by Django 3.1.7 on 2021-03-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_forumcomment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
