# Generated by Django 3.1.7 on 2021-03-14 18:35

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20210314_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcomment',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[500, 300], upload_to='images/'),
        ),
    ]
