# Generated by Django 3.1.7 on 2021-03-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20210314_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='body',
        ),
    ]
