# Generated by Django 3.1.7 on 2021-03-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_remove_forum_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentblog',
            old_name='body',
            new_name='answer',
        ),
    ]
