# Generated by Django 3.1.7 on 2021-03-14 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20210314_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentblog',
            old_name='answer',
            new_name='body',
        ),
    ]
