# Generated by Django 3.1.7 on 2021-03-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='notes',
            name='notes',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='qa',
            name='course',
            field=models.CharField(max_length=500),
        ),
    ]
